[package]
name = "lotl-typechk"
version = "0.1.0"
edition = "2024"

[dependencies]
lotl-ast = { workspace = true }
lotl-error = { workspace = true }

[dev-dependencies]
lotl-lexer = { workspace = true }
lotl-parser = { workspace = true }